M48
; DRILL file {KiCad (6.99.0-4266-g9b4505c6d2)} date 
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-13T11:25:53+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-4266-g9b4505c6d2)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X189.484Y-101.842
X189.484Y-107.622
T2
X150.62Y-106.075
X153.307Y-103.388
T0
M30
